### ISSUE TITLE
A few issues i found along the way while debugging

### ISSUE THREAD

**Issue by isrvamsi** [vmware/pmd#1]
1) In the pmd-demo sends RPC to the server to check for primes, 1 is reported as prime. 1 is not a  prime number.

2) In the file pmd/server/extras/fwmgmt_rpcapi.c, line 34, the server reports the usermgmt version instead of the firewall version.

**Comment by ppadmavilasom** [comment]
1. :) will fix.
2. will fix.

**Comment by ppadmavilasom** [comment]
https://github.com/vmware/pmd/commit/75b6c23ad9c361d879f88b247b65c230302b18b3
