### ISSUE TITLE
pmd-cli firewall usage is not up to date

### ISSUE THREAD

**Issue by iNode** [vmware/pmd#2]
`pmd-cli firewall` command shows usage output:

usage: pmd-cli [connection options] **fwmgmt** <command> [command options]

But if user will actually try to execute:
`pmd-cli fwmgmt`

he will get an error:

Component fwmgmt is not known
These are the current registered components
 'firewall' : firewall management
 'net' : network management
 'pkg' : package management
 'usr' : user management
Error(3) : Unknown error

Package info:
Name          : pmd-cli
Arch          : x86_64
Epoch         : 0
Version       : 0.0.5
Release       : 3.ph2
Install Size  :  58.79k 60200 (60200)
Repo          : @System
...

Name          : pmd-cli
Arch          : x86_64
Epoch         : 0
Version       : 0.0.5
Release       : 3.ph2

**Comment by ppadmavilasom** [comment]
@iNode, will fix. thanks for the report.

**Comment by ppadmavilasom** [comment]
https://github.com/vmware/pmd/commit/7ebef7f6b01329bff2dbc29bf32125446f593302
